ias_spbfkk/urls.py
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import path, include

from ias_spbfkk import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('site_spbfkk.urls', namespace='spbfkk')),
    path('accounts/', include('django.contrib.auth.urls'))
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

site_spbfkk/urls.py
from django.urls import path
from site_spbfkk.views import *

from site_spbfkk.views.events import ShowEvent, add_event_results, delete_event_result

app_name = 'site_spbfkk'
urlpatterns = [
    path('', SportsmenAll.as_view(), name='home'),
    path('show_rating_sportsmen/', SportsmenAllRating.as_view(), name='show_rating_sportsmen'),
    path('show_rating_coaches/', CoachesRatings.as_view(), name='show_rating_coaches'),
    path('coaches/', CoachesAll.as_view(), name='coaches'),
    path('addsportsmen/', add_sportsmen, name='addsportsmen'),
    path('sportsmen/<int:pk>/edit/', edit_sportsmen_data, name='edit_sportsmen_data'),
    path('sportsmen/<int:pk>/add_data/', add_sportsmen_data, name='add_sportsmen_data'),
    path('sportsmen/<int:pk>/delete/', delete_sportsmen, name='delete_sportsmen'),
    path('sportsmen/<int:pk>/', ShowDataSportsmen.as_view(), name='showsportsmen'),
    path('sportsmen/<int:pk>/documents/', sportsmen_documents, name='sportsmen_documents'),
    path('sportsmen/<int:pk>/documents/del', delete_sportsmen_documents, name='delete_sportsmen_documents'),
    path('sportsmen/<int:pk>/documents/edit/', edit_sportsmen_document, name='edit_sportsmen_document'),
    path('sports_hall/', SportsHallAll.as_view(), name='sports_hall'),
    path('sports_hall/<int:pk>/', ShowSportsHall.as_view(), name='show_sports_hall'),
    path('sports_hall/<int:pk>/add_schedule', add_schedule, name='add_schedule'),
    path('sports_hall/add_sports_hall/', add_sports_hall, name='add_sports_hall'),
    path('coaches/<int:pk>/', ShowDataCoach.as_view(), name='show_coach'),
    path('coaches/<int:pk>/add_data/', add_coach_data, name='add_coach_data'),
    path('coaches/<int:pk>/edit/', edit_coach_data, name='edit_coach_data'),
    path('coaches/<int:pk>/documents/', trainers_documents, name='trainers_documents'),
    path('coaches/<int:pk>/documents/del/', delete_trainers_documents, name='delete_trainers_documents'),
    path('coaches/<int:pk>/documents/edit/', edit_coach_document, name='edit_coach_document'),
    path('events/add_event/', add_event, name='add_event'),
    path('events/', AllEvents.as_view(), name='all_events'),
    path('events/<int:pk>/', ShowEvent.as_view(), name='show_event'),
    path('events/<int:pk>/edit_event/', edit_event_data, name='edit_event'),
    path('events/<int:pk>/documents/', add_event_documents, name='add_event_documents'),
    path('events/<int:pk>/documents/del/', delete_event_documents, name='del_event_documents'),
    path('events/<int:pk>/documents/edit/', edit_event_document, name='edit_event_document'),
    path('events/<int:pk>/add_results/', add_event_results, name='add_event_results'),
    path('events/<int:pk>/add_results/del/', delete_event_result, name='delete_event_result'),
    path('events/<int:pk>/add_applications/', add_event_applications, name='add_event_applications'),
    path('events/<int:pk>/add_applications/del/', delete_event_applications, name='delete_event_applications'),
    path('export_excel', export_excel, name='export_excel'),

]

site_spbfkk/models.py
from django.contrib.auth.models import User
from django.db import models

from django.urls import reverse
from django.utils import timezone

SPORTS_CATEGORY = [
        ('3J', '3 юношеский разряд'),
        ('2J', '2 юношеский разряд'),
        ('1J', '1 юношеский разряд'),
        ('3C', '3 разряд'),
        ('2C', '2 разряд'),
        ('1C', '1 разярд'),
        ('KMS', 'КМС'),
        ('MS', 'МС'),
        ('MSIC', 'МСМК'),
        ('HMS', 'ЗМС'),
        ('NN', 'Не выбрано'),
    ]

DEGREE = [
        ('KU', 'Кю'),
        ('DAN', 'Дан'),
    ]

DEGREE_LEVEL = [
        ('O', '1'),
        ('TW', '2'),
        ('T', '3'),
        ('F', '4'),
        ('Fv', '5'),
        ('S', '6'),
        ('Sn', '7'),
        ('E', '8'),
        ('N', '9'),
        ('TE', '10'),
        ('En', '11'),
        ('Z', '0'),
        ('NN', 'Не выбрано'),
    ]

JUDGING_CATEGORY = [
        ('3JC', '3'),
        ('2JC', '2'),
        ('1JC', '1'),
        ('JRC', 'СВК'),
        ('N', 'Отсутствует'),
    ]

class SportsClub(models.Model):
    club_name = models.CharField(max_length=30, verbose_name='Название клуба')
    year_of_foundation = models.DateField(verbose_name='Дата основания')
    head_of_the_club = models.ForeignKey('Coach',
                                         on_delete=models.SET_NULL,
                                         blank=True, null=True,
                                         verbose_name='Руководитель',
                                         )
    date_added = models.DateField(verbose_name='Дата добавления', default=timezone.now)
    archive = models.BooleanField(default=False, verbose_name='Архив')

    class Meta:
        verbose_name = 'Спортивный клуб'
        verbose_name_plural = 'Спортивные клубы'
        ordering = ['club_name']

    def __str__(self):
        return self.club_name

    def get_absolut_url(self):
        return f'/sportsclub/{self.pk}/'


class Coach(models.Model):
    club = models.ForeignKey(SportsClub,
                                  on_delete=models.SET_NULL,
                                  blank=True, null=True,
                                  verbose_name='Клуб',
                                  )
    coach = models.ForeignKey(User, verbose_name='Пользователь', on_delete=models.SET_NULL, null=True)
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    first_name = models.CharField(max_length=15, verbose_name='Имя')
    patronymic = models.CharField(max_length=20, verbose_name='Отчество')
    date_added = models.DateField(verbose_name='Дата добавления', default=timezone.now)


    class Meta:
        verbose_name = 'Тренер'
        verbose_name_plural = 'Тренеры'
        ordering = ['club', 'last_name', 'first_name', 'patronymic']
        app_label = 'site_spbfkk'

    def __str__(self):
       # if self.User:
#            return self.User.laste_name + ' ' + self.User.first_name

        full_name = self.last_name + ' ' + self.first_name + ' ' + self.patronymic
        return full_name

    def get_absolut_url(self):
        return f'/coaches/{self.pk}/'

    # def get_absolut_url(self):
    #     return reverse('coaches', kwargs={'coach_id': self.pk})


class CoachDate(models.Model):
    coach = models.ForeignKey(Coach,
                              on_delete=models.CASCADE,
                              verbose_name='Тренер',
                              )
    year_of_birth = models.DateField(verbose_name='Дата рождения')
    coaching_title = models.TextField(verbose_name='Звания')
    sports_category = models.CharField(choices=SPORTS_CATEGORY,
                                       default='NN',
                                       verbose_name='Спортивный разряд',
                                       max_length=18,
                                       )
    degree = models.CharField(choices=DEGREE,
                              default='KU',
                              verbose_name='Степень',
                              max_length=3,
                              )
    degree_level = models.CharField(choices=DEGREE_LEVEL,
                                    default='Z',
                                    verbose_name='Градация степени',
                                    max_length=10,
                                    )
    judging_category = models.CharField(choices=JUDGING_CATEGORY,
                                        default='N',
                                        verbose_name='Судейская категория',
                                        max_length=11,
                                        )
    sports_results = models.TextField(verbose_name='Спортивные результаты', default=None)
    coach_rating = models.PositiveIntegerField(verbose_name='Рейтинг тренера', default=0)
    education = models.TextField(verbose_name='Образование')
    phone_number = models.CharField(max_length=11, verbose_name='Номер телефона')
    e_mail = models.EmailField(verbose_name='Адрес электронной почты')
    archive = models.BooleanField(default=False, verbose_name='Архив')



class SportsHall(models.Model):
    sports_club = models.ForeignKey(SportsClub,
                                    on_delete=models.SET_NULL,
                                    blank=True, null=True,
                                    verbose_name='Спортиный клуб')
    coach = models.ForeignKey(Coach,
                              on_delete=models.SET_NULL,
                              blank=True, null=True,
                              verbose_name='Тренер',
                              )
    region = models.CharField(max_length=30, verbose_name='Регион')
    locality = models.CharField(max_length=20, verbose_name='Населённый пункт')
    district = models.CharField(max_length=20, verbose_name='Район')
    street = models.CharField(max_length=20, verbose_name='Улица')
    house_number = models.CharField(max_length=5, verbose_name='Номер дома')

    def get_absolut_url(self):
        return f'/sports_hall/{self.pk}/'

    # def __str__(self):
    #     return self.

class TrainingSchedule(models.Model):
    WEEK = [
        ('MD', 'Понедельник'),
        ('TS', 'Вторник'),
        ('WD', 'Среда'),
        ('TH', 'Четверг'),
        ('FD', 'Пятница'),
        ('SD', 'Суббота'),
        ('SND', 'Воскресенье'),
        ('NN', 'Не выбрано')
    ]
    address_hall = models.ForeignKey(SportsHall,
                                     on_delete=models.CASCADE,
                                     verbose_name='Адрес зала'
                                     )
    day_week = models.CharField(choices=WEEK,
                                default='NN',
                                verbose_name='День недели',
                                max_length=11,
                                )
    training_time = models.CharField(max_length=11, verbose_name='Время')
    category_students = models.CharField(max_length=30, verbose_name='Категория занимающихся')

class TrainersDocuments(models.Model):
    coach = models.ForeignKey(Coach,
                              on_delete=models.CASCADE,
                              verbose_name='Тренер',
                              )
    name_document = models.CharField(max_length=30, verbose_name='Название документа')
    date_issue = models.DateField(verbose_name='Дата выдачи')
    validity_period = models.DateField(verbose_name='Действителен до') # значение по умолчанию?
    number_document = models.CharField(max_length=15, verbose_name='Номер документа')
    issued_by_whom = models.CharField(max_length=30, verbose_name='Кем выдан')
    scanned_copy = models.FileField(verbose_name='Скан-копия', blank=True, upload_to='coaches/%Y-%m-%d')
    date_added = models.DateField(verbose_name='Дата добавления', default=timezone.now, blank=True)

    def get_absolut_url(self):
        return f'/documents/{self.pk}/'



class Finance(models.Model):
    TYPE_FINANCE = [
        ('T', 'Налог'),
        ('IFE', 'Инструкторский взнос'),
        ('AF', 'Годовой взнос'),
        ('NN', 'Не выбрано'),
    ]

    coach = models.ForeignKey(Coach,
                              on_delete=models.CASCADE,
                              verbose_name='Тренер'
                              )
    payment_date = models.DateField(verbose_name='Дата взноса')
    type_finance = models.CharField(choices=TYPE_FINANCE,
                                    default='NN',
                                    verbose_name='Вид взноса',
                                    max_length=20,
                                    )
    contrib_amount = models.PositiveSmallIntegerField(verbose_name='Сумма взноса')

class Sportsmen(models.Model):
    class SexChoices(models.TextChoices):
        MALE = 'Мужской'
        FEMALE = 'Женский'

    club = models.ForeignKey(SportsClub,
                                  on_delete=models.SET_NULL,
                                  blank=True, null=True,
                                  verbose_name='Клуб',
                                  )
    coach = models.ForeignKey(Coach,
                              on_delete=models.SET_NULL,
                              blank=True, null=True,
                              verbose_name='Тренер',
                              )
    last_name = models.CharField(max_length=20, verbose_name='Фамилия')
    first_name = models.CharField(max_length=15, verbose_name='Имя')
    patronymic = models.CharField(max_length=20, verbose_name='Отчество')
    date_added = models.DateField(default=timezone.now, verbose_name='Дата добваления')
    sex = models.CharField(choices=SexChoices.choices, verbose_name='Пол', max_length=20, default=SexChoices.MALE)

    def __str__(self):
        full_name = self.last_name + ' ' + self.first_name + ' ' + self.patronymic
        return full_name

    def get_absolut_url(self):
        return f'/sportsmen/{self.pk}/'

class SportsmenDate(models.Model):
    WEIGHT_CATEGORY_MALE = [
        ('825', '8-9 лет до 25 кг'),
        ('830', '8-9 лет до 30 кг'),

site_spbfkk/views/clubs.py
from django.shortcuts import redirect, render
from django.views.generic import ListView

from site_spbfkk.forms import AddSportsHall, AddSchedule
from site_spbfkk.models import SportsClub, SportsHall, Coach, TrainingSchedule


class SportsHallAll(ListView):
    """Класс для отображения списка спортивных клубов"""
    model = SportsHall
    template_name = 'site_spbfkk/sports_hall_all.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        # context['sportshall'] = SportsHall.objects.get(pk=self.kwargs['pk'])
        return context

def add_sports_hall(request):
    """ Функция для добавления спортивного зала """
    # sports_hall = SportsHall.objects.get(pk=pk)
    if request.method == 'POST':
        form = AddSportsHall(request.POST)
        if form.is_valid():
            form.save()
            return redirect('spbfkk:coaches')
    else:
        form = AddSportsHall()
    return render(request, 'site_spbfkk/add_sports_hall.html', {'form': form,
                                                             'title': 'Добавление спортивного зала',
                                                              })

class ShowSportsHall(ListView):
    """ Класс для отображения расписания спортивного зала """
    model = TrainingSchedule
    template_name = 'site_spbfkk/show_schedule.html'

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        context['sportshall'] = SportsHall.objects.get(pk=self.kwargs['pk'])
        # context['schedule'] = TrainingSchedule.objects.filter(adress_hall__pk=self.kwargs['pk'])
        # context['clubs'] = SportsClub.objects.get(pk=self.kwargs['pk'])
        # context['documents'] = TrainersDocuments.objects.filter(coach__pk=self.kwargs['pk'])
        return context


    def get_queryset(self):
        return TrainingSchedule.objects.filter(address_hall_id=self.kwargs['pk'])

def add_schedule(request, pk):
    """ Функция для добавления расписания"""
    # sports_hall = SportsHall.objects.get(pk=pk)
    if request.method == 'POST':
        form = AddSchedule(request.POST)
        if form.is_valid():
            form.save()
            return redirect('spbfkk:coaches')
    else:
        form = AddSchedule()
    return render(request, 'site_spbfkk/add_schedule.html', {'form': form,
                                                             'title': 'Добавление расписания',
                                                              })

site_spbfkk/views/logic.py
from io import BytesIO

from django.contrib.auth import logout
from django.shortcuts import redirect
from xlsxwriter import Workbook

from site_spbfkk.models import Sportsmen


def logout_user(request):
    logout(request)
    return redirect('login')

def count_rating(rating, status, result):
    """Функция подсчёта рейтинга спортсмена"""

    value = {
             'DC': {'1P': 15, '2P': 10, '3P': 5, '4P': 0},
             'RG': {'1P': 30, '2P': 20, '3P': 10, '4P': 0},
             'AR': {'1P': 40, '2P': 30, '3P': 20, '4P': 0},
             'IN': {'1P': 40, '2P': 30, '3P': 20, '4P': 0},
             'CE': {'1P': 70, '2P': 60, '3P': 50, '4P': 40},
             'CR': {'1P': 100, '2P': 80, '3P': 60, '4P': 50},
             'CJ': {'1P': 110, '2P': 100, '3P': 80, '4P': 70},
             'CW': {'1P': 200, '2P': 170, '3P': 120, '4P': 100},
             }

    rating_value = value[status][result]
    new_rating = rating + rating_value
    return new_rating


def export_to_xls():
    output = BytesIO()
    wb = Workbook(output, {'in_memory': True})
    sheet = wb.add_worksheet()

    for i, sportsmen in enumerate(Sportsmen.objects.all()):
        sheet.write(i, 0, sportsmen.first_name)
        sheet.write(i, 1, sportsmen.last_name)

    wb.close()
    output.seek(0)
    return output

site_spbfkk/templates/site_spbfkk/add_event_applications.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
<h1>{{event}}</h1>
<h2>{{title}}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Добавить</button>
</form>


{% for r in applications %}
<ul>
{{r.sportsmen}} | {{r.sportsmen.sportsmensdata.first.get_weight_category_male_display}}
<form action="{% url 'spbfkk:delete_event_applications' pk=r.pk %}">
    <button type="submit">Удалить заявку</button>
    </form>
</ul>
    {% endfor %}

{% endblock content %}

site_spbfkk/templates/site_spbfkk/add_event_results.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
<h1>{{event}}</h1>
<h2>{{title}}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Добавить</button>
</form>


{% for r in result %}
<ul>
{{r.sportsmen}} | {{r.sportsmen.sportsmensdata.first.get_weight_category_male_display}} | {{r.get_result_display}}
<form action="{% url 'spbfkk:delete_event_result' pk=r.pk %}">
    <button type="submit">Удалить результат</button>
    </form>
</ul>
    {% endfor %}

{% endblock content %}

site_spbfkk/templates/site_spbfkk/add_schedule.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
<h2>{{title}}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Сохранить</button>
</form>
{% endblock content %}

site_spbfkk/templates/site_spbfkk/add_sportsmen_data.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
<h1>{{sportsmen}}</h1>
<h2>{{title}}</h2>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Сохранить</button>
</form>
{% endblock content %}

site_spbfkk/templates/site_spbfkk/add_sportsmen_documents.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
<h1>{{sportsmen}}</h1>
<h1>{{sportsmen_document.sportsmen}}</h1>
<h2>{{title}}</h2>

<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type = "submit">Сохранить</button>
</form>
{% endblock content %}

site_spbfkk/templates/site_spbfkk/show_data_coach.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
{% if not object_list %}
<h1>{{coach}}</h1>
<form action="{% url 'spbfkk:add_coach_data' pk=coach.pk %}">
    <button type="submit">Добавить данные</button>
</form>
{% endif %}


{% for c in object_list %}

<h1>{{c.coach}}</h1>
<h2>Данные тренера</h2>
<form action="{% url 'spbfkk:edit_coach_data' pk=c.pk %}">
    <button type="submit">Редактировать данные</button>
    </form>

<form action="{% url 'spbfkk:trainers_documents' pk=coach.pk %}">
    <button type="submit">Добавить документ</button>
    </form>
<p>Спортивный клуб: {{c.coach.club}}</p>
<p>Дата рождения: {{c.year_of_birth}}</p>
<p>Образование: {{c.education}}</p>
<p>Звания: {{c.coaching_title}}</p>
<p>Спортивный разряд: {{c.get_sports_category_display}}</p>
<p>Градация степени: {{c.get_degree_level_display}} {{c.get_degree_display}}</p>
<p>Судейская категория: {{c.get_judging_category_display}}</p>
<p>Спортивные результаты: {{c.sports_results}}</p>
<p>Рейтинг тренера: {{c.coach_rating}}</p>
<h2>Контактные данные</h2>
<p>Номер телефона: {{c.phone_number}}</p>
<p>E-mail: {{c.e_mail}}</p>



{% endfor %}

{% if documents %}
<h2>Документы</h2>
{% for d in documents %}
<p>Имя документа: {{d.name_document}}</p>
<p>Дата выдачи: {{d.date_issue}}</p>
<p>Действителен до: {{d.validity_period}}</p>
<p>Номер документа: {{d.number_document}}</p>
<p>Кем выдан: {{d.issued_by_whom}}</p>

    {% if d.scanned_copy %}
<p>Скан-копия: <a href="{{ d.scanned_copy.url }}" download>{{d.scanned_copy}}</a></p>
    {% endif %}

<p>Дата добавления документа: {{d.date_added}}</p>

<form action="{% url 'spbfkk:delete_trainers_documents' pk=d.pk %}">
    <button type="submit">Удалить документ</button>
    </form>

<form action="{% url 'spbfkk:edit_coach_document' pk=d.pk %}">
    <button type="submit">Редактировать документ</button>
    </form>
<p>------------------</p>
{% endfor %}
{% endif %}

{% endblock content %}

site_spbfkk/templates/site_spbfkk/show_data_sportsmen.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
{% if not object_list %}
<h1>{{sportsmen}}</h1>
<form action="{% url 'spbfkk:add_sportsmen_data' pk=sportsmen.pk %}">
    <button type="submit">Добавить данные</button>
</form>
{% endif %}

{% for c in object_list %}

<h1>{{c}}</h1>
<h2>Данные спортсмена</h2>
<form action="{% url 'spbfkk:edit_sportsmen_data' pk=c.pk %}">
    <button type="submit">Редактировать данные</button>
    </form>

<form action="{% url 'spbfkk:sportsmen_documents' pk=sportsmen.pk %}">
    <button type="submit">Добавить документ</button>
    </form>

<form action="{% url 'spbfkk:delete_sportsmen' pk=sportsmen.pk %}">
    <button type="submit">Удалить спортсмена</button>
    </form>
<p>Спортивный клуб: {{c.sportsmen.club}}</p>
<p>Тренер: {{c.sportsmen.coach}}</p>
<p>Дата рождения: {{c.year_of_birth}}</p>
<p>Звания: {{c.sportsmen_title}}</p>
<p>Спортивный разряд: {{c.get_sports_category_display}}</p>
<p>Градация степени: {{c.get_degree_level_display}} {{c.get_degree_display}} </p>
{% if c.weight_category_male %}
<p>Весовая категория: {{c.get_weight_category_male_display}}</p>
{% endif %}
{% if c.weight_category_female %}
<p>Весовая категория: {{c.get_weight_category_female_display}}</p>
{% endif %}
<p>Судейская категория: {{c.get_judging_category_display}}</p>
<p>Спортивный рейтинг: {{c.sports_rating}}</p>
<p>Спортивные результаты: {{c.sports_results}}</p>
<p>Годовой взнос: {{c.annual_fee}} Дата взноса: {{c.annual_fee_date}}</p>
<h2>Контактные данные</h2>
<p>Номер телефона: {{c.phone_number}}</p>
<p>E-mail: {{c.e_mail}}</p>
<p>ФИО родителя: {{c.flp_parents_1}}</p>
<p>Номер телефона родителя: {{c.phone_number_par_1}}</p>
{% if c.flp_parents_2 %}
<p>ФИО родителя: {{c.flp_parents_2}}</p>
{% endif %}
{% if c.phone_number_par_2 %}
<p>Номер телефона родителя: {{c.phone_number_par_2}}</p>
{% endif %}
{% endfor %}

{% if documents %}
<h2>Документы</h2>
{% for d in documents %}
<p>Имя документа: {{d.name_document}}</p>
<p>Дата выдачи: {{d.date_issue}}</p>
<p>Действителен до: {{d.validity_period}}</p>
<p>Номер документа: {{d.number_document}}</p>
<p>Кем выдан: {{d.issued_by_whom}}</p>

    {% if d.scanned_copy %}
<p>Скан-копия: <a href="{{ d.scanned_copy.url }}" download>{{d.scanned_copy}}</a></p>
    {% endif %}

<p>Дата добавления документа: {{d.date_added}}</p>

<form action="{% url 'spbfkk:delete_sportsmen_documents' pk=d.pk %}">
    <button type="submit">Удалить документ</button>
    </form>

<form action="{% url 'spbfkk:edit_sportsmen_document' pk=d.pk %}">
    <button type="submit">Редактировать документ</button>
    </form>
<p>________________________</p>
{% endfor %}
{% endif %}
{% endblock content %}

site_spbfkk/templates/site_spbfkk/show_event.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}


{% for e in object_list %}

<h1>{{e}}</h1>
<h2>Данные мероприятия</h2>

<form action="{% url 'spbfkk:edit_event' pk=e.pk %}">
    <button type="submit">Редактировать данные</button>
    </form>

<form action="{% url 'spbfkk:add_event_documents' pk=event.pk %}">
    <button type="submit">Добавить документ</button>
    </form>

<form action="{% url 'spbfkk:add_event_applications' pk=event.pk %}">
    <button type="submit">Добавить заявку</button>
    </form>

{% if e.type_events == 'CO' %}
<form action="{% url 'spbfkk:add_event_results' pk=event.pk %}">
    <button type="submit">Добавить результаты</button>
    </form>
{% endif %}

<p>Дата начала мероприятия: {{e.date_start_events}}</p>
<p>Дата окончания мероприятия: {{e.date_end_events}}</p>
<p>Дата окончания подачи заявок: {{e.date_end_applications}}</p>
<p>Ограничение по Кю: {{e.limit_ku}}</p>
<p>Ограничение по возрасту: {{e.limit_age}}</p>
<p>Тип мероприятия: {{e.get_type_events_display}}</p>
<p>Статус мероприятия: {{e.get_status_events_display}}</p>

{% endfor %}

{% if documents %}
<h2>Документы</h2>
{% for d in documents %}
<p>Имя документа: {{d.name_doc}}</p>
<p>Дата документа: {{d.date_doc}}</p>
<p>Номер документа: {{d.series_doc}}</p>

    {% if d.scan_doc %}
<p>Скан-копия: <a href="{{ d.scan_doc.url }}" download>{{d.scan_doc}}</a></p>
    {% endif %}


<form action="{% url 'spbfkk:del_event_documents' pk=d.pk %}">
    <button type="submit">Удалить документ</button>
    </form>

<form action="{% url 'spbfkk:edit_event_document' pk=d.pk %}">
    <button type="submit">Редактировать документ</button>
    </form>
<p>------------------</p>
{% endfor %}
{% endif %}

{% endblock content %}

site_spbfkk/templates/site_spbfkk/show_schedule.html
{% extends 'site_spbfkk/base.html' %}

{% block content %}
{% if not object_list %}
<h1>Добавление расписания</h1>
<form action="{% url 'spbfkk:add_schedule' pk=sportshall.pk %}">
    <button type="submit">Добавить расписание</button>
</form>
{% endif %}


{% for c in object_list %}

<h2>Расписание зала:</h2>
<form action="{% url 'spbfkk:add_schedule' pk=sportshall.pk %}">
    <button type="submit">Добавить расписание</button>
</form>
<p>{{c.get_day_week_display}} - время: {{c.training_time}}, категория занимающихся: {{c.category_students}}</p>

{% endfor %}


{% endblock content %}